//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0")]
[System.Xml.Serialization.XmlRootAttribute("ObrazacPDV", Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0", IsNullable=false)]
public partial class sObrazacPDV {
    
    private sPDVmetapodaci metapodaciField;
    
    private sZaglavlje zaglavljeField;
    
    private sTijelo tijeloField;
    
    private string verzijaShemeField;
    
    public sObrazacPDV() {
        this.verzijaShemeField = "9.0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
    public sPDVmetapodaci Metapodaci {
        get {
            return this.metapodaciField;
        }
        set {
            this.metapodaciField = value;
        }
    }
    
    /// <remarks/>
    public sZaglavlje Zaglavlje {
        get {
            return this.zaglavljeField;
        }
        set {
            this.zaglavljeField = value;
        }
    }
    
    /// <remarks/>
    public sTijelo Tijelo {
        get {
            return this.tijeloField;
        }
        set {
            this.tijeloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string verzijaSheme {
        get {
            return this.verzijaShemeField;
        }
        set {
            this.verzijaShemeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
[System.Xml.Serialization.XmlRootAttribute("Metapodaci", Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0", IsNullable=false)]
public partial class sPDVmetapodaci {
    
    private sNaslovTemeljni naslovField;
    
    private sAutorTemeljni autorField;
    
    private sDatumTemeljni datumField;
    
    private sFormatTemeljni formatField;
    
    private sJezikTemeljni jezikField;
    
    private sIdentifikatorTemeljni identifikatorField;
    
    private sUskladjenost uskladjenostField;
    
    private sTipTemeljni tipField;
    
    private sAdresantTemeljni adresantField;
    
    /// <remarks/>
    public sNaslovTemeljni Naslov {
        get {
            return this.naslovField;
        }
        set {
            this.naslovField = value;
        }
    }
    
    /// <remarks/>
    public sAutorTemeljni Autor {
        get {
            return this.autorField;
        }
        set {
            this.autorField = value;
        }
    }
    
    /// <remarks/>
    public sDatumTemeljni Datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
    
    /// <remarks/>
    public sFormatTemeljni Format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    public sJezikTemeljni Jezik {
        get {
            return this.jezikField;
        }
        set {
            this.jezikField = value;
        }
    }
    
    /// <remarks/>
    public sIdentifikatorTemeljni Identifikator {
        get {
            return this.identifikatorField;
        }
        set {
            this.identifikatorField = value;
        }
    }
    
    /// <remarks/>
    public sUskladjenost Uskladjenost {
        get {
            return this.uskladjenostField;
        }
        set {
            this.uskladjenostField = value;
        }
    }
    
    /// <remarks/>
    public sTipTemeljni Tip {
        get {
            return this.tipField;
        }
        set {
            this.tipField = value;
        }
    }
    
    /// <remarks/>
    public sAdresantTemeljni Adresant {
        get {
            return this.adresantField;
        }
        set {
            this.adresantField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sNaslovTemeljni {
    
    private string dcField;
    
    private string valueField;
    
    public sNaslovTemeljni() {
        this.dcField = "http://purl.org/dc/elements/1.1/title";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0")]
public partial class sIsporukaNekretnina {
    
    private decimal vrijednostField;
    
    private string brojField;
    
    /// <remarks/>
    public decimal Vrijednost {
        get {
            return this.vrijednostField;
        }
        set {
            this.vrijednostField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Broj {
        get {
            return this.brojField;
        }
        set {
            this.brojField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0")]
public partial class sIsporuka {
    
    private decimal vrijednostField;
    
    private decimal porezField;
    
    /// <remarks/>
    public decimal Vrijednost {
        get {
            return this.vrijednostField;
        }
        set {
            this.vrijednostField = value;
        }
    }
    
    /// <remarks/>
    public decimal Porez {
        get {
            return this.porezField;
        }
        set {
            this.porezField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0")]
public partial class sTijelo {
    
    private decimal podatak000Field;
    
    private decimal podatak100Field;
    
    private decimal podatak101Field;
    
    private decimal podatak102Field;
    
    private decimal podatak103Field;
    
    private decimal podatak104Field;
    
    private decimal podatak105Field;
    
    private decimal podatak106Field;
    
    private decimal podatak107Field;
    
    private decimal podatak108Field;
    
    private decimal podatak109Field;
    
    private decimal podatak110Field;
    
    private sIsporuka podatak200Field;
    
    private sIsporuka podatak201Field;
    
    private sIsporuka podatak202Field;
    
    private sIsporuka podatak203Field;
    
    private sIsporuka podatak204Field;
    
    private sIsporuka podatak205Field;
    
    private sIsporuka podatak206Field;
    
    private sIsporuka podatak207Field;
    
    private sIsporuka podatak208Field;
    
    private sIsporuka podatak209Field;
    
    private sIsporuka podatak210Field;
    
    private sIsporuka podatak211Field;
    
    private sIsporuka podatak212Field;
    
    private sIsporuka podatak213Field;
    
    private sIsporuka podatak214Field;
    
    private sIsporuka podatak215Field;
    
    private sIsporuka podatak300Field;
    
    private sIsporuka podatak301Field;
    
    private sIsporuka podatak302Field;
    
    private sIsporuka podatak303Field;
    
    private sIsporuka podatak304Field;
    
    private sIsporuka podatak305Field;
    
    private sIsporuka podatak306Field;
    
    private sIsporuka podatak307Field;
    
    private sIsporuka podatak308Field;
    
    private sIsporuka podatak309Field;
    
    private sIsporuka podatak310Field;
    
    private sIsporuka podatak311Field;
    
    private sIsporuka podatak312Field;
    
    private sIsporuka podatak313Field;
    
    private sIsporuka podatak314Field;
    
    private decimal podatak315Field;
    
    private decimal podatak400Field;
    
    private decimal podatak500Field;
    
    private decimal podatak600Field;
    
    private decimal podatak700Field;
    
    private decimal podatak810Field;
    
    private decimal podatak811Field;
    
    private decimal podatak812Field;
    
    private decimal podatak813Field;
    
    private decimal podatak814Field;
    
    private decimal podatak815Field;
    
    private decimal podatak820Field;
    
    private decimal podatak830Field;
    
    private sIsporukaNekretnina podatak831Field;
    
    private sIsporukaNekretnina podatak832Field;
    
    private sIsporukaNekretnina podatak833Field;
    
    private decimal podatak840Field;
    
    private decimal podatak850Field;
    
    private decimal podatak860Field;
    
    private bool podatak870Field;
    
    private decimal povratField;
    
    private string povratIBANField;
    
    private decimal predujamField;
    
    private bool predujamFieldSpecified;
    
    private decimal ustupPovrataField;
    
    private bool ustupPovrataFieldSpecified;
    
    /// <remarks/>
    public decimal Podatak000 {
        get {
            return this.podatak000Field;
        }
        set {
            this.podatak000Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak100 {
        get {
            return this.podatak100Field;
        }
        set {
            this.podatak100Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak101 {
        get {
            return this.podatak101Field;
        }
        set {
            this.podatak101Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak102 {
        get {
            return this.podatak102Field;
        }
        set {
            this.podatak102Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak103 {
        get {
            return this.podatak103Field;
        }
        set {
            this.podatak103Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak104 {
        get {
            return this.podatak104Field;
        }
        set {
            this.podatak104Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak105 {
        get {
            return this.podatak105Field;
        }
        set {
            this.podatak105Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak106 {
        get {
            return this.podatak106Field;
        }
        set {
            this.podatak106Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak107 {
        get {
            return this.podatak107Field;
        }
        set {
            this.podatak107Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak108 {
        get {
            return this.podatak108Field;
        }
        set {
            this.podatak108Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak109 {
        get {
            return this.podatak109Field;
        }
        set {
            this.podatak109Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak110 {
        get {
            return this.podatak110Field;
        }
        set {
            this.podatak110Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak200 {
        get {
            return this.podatak200Field;
        }
        set {
            this.podatak200Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak201 {
        get {
            return this.podatak201Field;
        }
        set {
            this.podatak201Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak202 {
        get {
            return this.podatak202Field;
        }
        set {
            this.podatak202Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak203 {
        get {
            return this.podatak203Field;
        }
        set {
            this.podatak203Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak204 {
        get {
            return this.podatak204Field;
        }
        set {
            this.podatak204Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak205 {
        get {
            return this.podatak205Field;
        }
        set {
            this.podatak205Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak206 {
        get {
            return this.podatak206Field;
        }
        set {
            this.podatak206Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak207 {
        get {
            return this.podatak207Field;
        }
        set {
            this.podatak207Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak208 {
        get {
            return this.podatak208Field;
        }
        set {
            this.podatak208Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak209 {
        get {
            return this.podatak209Field;
        }
        set {
            this.podatak209Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak210 {
        get {
            return this.podatak210Field;
        }
        set {
            this.podatak210Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak211 {
        get {
            return this.podatak211Field;
        }
        set {
            this.podatak211Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak212 {
        get {
            return this.podatak212Field;
        }
        set {
            this.podatak212Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak213 {
        get {
            return this.podatak213Field;
        }
        set {
            this.podatak213Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak214 {
        get {
            return this.podatak214Field;
        }
        set {
            this.podatak214Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak215 {
        get {
            return this.podatak215Field;
        }
        set {
            this.podatak215Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak300 {
        get {
            return this.podatak300Field;
        }
        set {
            this.podatak300Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak301 {
        get {
            return this.podatak301Field;
        }
        set {
            this.podatak301Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak302 {
        get {
            return this.podatak302Field;
        }
        set {
            this.podatak302Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak303 {
        get {
            return this.podatak303Field;
        }
        set {
            this.podatak303Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak304 {
        get {
            return this.podatak304Field;
        }
        set {
            this.podatak304Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak305 {
        get {
            return this.podatak305Field;
        }
        set {
            this.podatak305Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak306 {
        get {
            return this.podatak306Field;
        }
        set {
            this.podatak306Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak307 {
        get {
            return this.podatak307Field;
        }
        set {
            this.podatak307Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak308 {
        get {
            return this.podatak308Field;
        }
        set {
            this.podatak308Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak309 {
        get {
            return this.podatak309Field;
        }
        set {
            this.podatak309Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak310 {
        get {
            return this.podatak310Field;
        }
        set {
            this.podatak310Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak311 {
        get {
            return this.podatak311Field;
        }
        set {
            this.podatak311Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak312 {
        get {
            return this.podatak312Field;
        }
        set {
            this.podatak312Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak313 {
        get {
            return this.podatak313Field;
        }
        set {
            this.podatak313Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporuka Podatak314 {
        get {
            return this.podatak314Field;
        }
        set {
            this.podatak314Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak315 {
        get {
            return this.podatak315Field;
        }
        set {
            this.podatak315Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak400 {
        get {
            return this.podatak400Field;
        }
        set {
            this.podatak400Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak500 {
        get {
            return this.podatak500Field;
        }
        set {
            this.podatak500Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak600 {
        get {
            return this.podatak600Field;
        }
        set {
            this.podatak600Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak700 {
        get {
            return this.podatak700Field;
        }
        set {
            this.podatak700Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak810 {
        get {
            return this.podatak810Field;
        }
        set {
            this.podatak810Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak811 {
        get {
            return this.podatak811Field;
        }
        set {
            this.podatak811Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak812 {
        get {
            return this.podatak812Field;
        }
        set {
            this.podatak812Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak813 {
        get {
            return this.podatak813Field;
        }
        set {
            this.podatak813Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak814 {
        get {
            return this.podatak814Field;
        }
        set {
            this.podatak814Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak815 {
        get {
            return this.podatak815Field;
        }
        set {
            this.podatak815Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak820 {
        get {
            return this.podatak820Field;
        }
        set {
            this.podatak820Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak830 {
        get {
            return this.podatak830Field;
        }
        set {
            this.podatak830Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporukaNekretnina Podatak831 {
        get {
            return this.podatak831Field;
        }
        set {
            this.podatak831Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporukaNekretnina Podatak832 {
        get {
            return this.podatak832Field;
        }
        set {
            this.podatak832Field = value;
        }
    }
    
    /// <remarks/>
    public sIsporukaNekretnina Podatak833 {
        get {
            return this.podatak833Field;
        }
        set {
            this.podatak833Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak840 {
        get {
            return this.podatak840Field;
        }
        set {
            this.podatak840Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak850 {
        get {
            return this.podatak850Field;
        }
        set {
            this.podatak850Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Podatak860 {
        get {
            return this.podatak860Field;
        }
        set {
            this.podatak860Field = value;
        }
    }
    
    /// <remarks/>
    public bool Podatak870 {
        get {
            return this.podatak870Field;
        }
        set {
            this.podatak870Field = value;
        }
    }
    
    /// <remarks/>
    public decimal Povrat {
        get {
            return this.povratField;
        }
        set {
            this.povratField = value;
        }
    }
    
    /// <remarks/>
    public string PovratIBAN {
        get {
            return this.povratIBANField;
        }
        set {
            this.povratIBANField = value;
        }
    }
    
    /// <remarks/>
    public decimal Predujam {
        get {
            return this.predujamField;
        }
        set {
            this.predujamField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool PredujamSpecified {
        get {
            return this.predujamFieldSpecified;
        }
        set {
            this.predujamFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public decimal UstupPovrata {
        get {
            return this.ustupPovrataField;
        }
        set {
            this.ustupPovrataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UstupPovrataSpecified {
        get {
            return this.ustupPovrataFieldSpecified;
        }
        set {
            this.ustupPovrataFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0")]
public partial class sZastupnik {
    
    private string[] itemsField;
    
    private ItemsChoiceType2[] itemsElementNameField;
    
    private string itemField;
    
    private ItemChoiceType1 itemElementNameField;
    
    private sAdresa adresaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Ime", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Naziv", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prezime", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType2[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OIB", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PDVID", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType1 ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    public sAdresa Adresa {
        get {
            return this.adresaField;
        }
        set {
            this.adresaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0", IncludeInSchema=false)]
public enum ItemsChoiceType2 {
    
    /// <remarks/>
    Ime,
    
    /// <remarks/>
    Naziv,
    
    /// <remarks/>
    Prezime,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0", IncludeInSchema=false)]
public enum ItemChoiceType1 {
    
    /// <remarks/>
    OIB,
    
    /// <remarks/>
    PDVID,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0")]
public partial class sAdresa {
    
    private string mjestoField;
    
    private string ulicaField;
    
    private string brojField;
    
    /// <remarks/>
    public string Mjesto {
        get {
            return this.mjestoField;
        }
        set {
            this.mjestoField = value;
        }
    }
    
    /// <remarks/>
    public string Ulica {
        get {
            return this.ulicaField;
        }
        set {
            this.ulicaField = value;
        }
    }
    
    /// <remarks/>
    public string Broj {
        get {
            return this.brojField;
        }
        set {
            this.brojField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0")]
public partial class sPoslovniSubjekt {
    
    private string[] itemsField;
    
    private ItemsChoiceType1[] itemsElementNameField;
    
    private string oIBField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Ime", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Naziv", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prezime", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    public string OIB {
        get {
            return this.oIBField;
        }
        set {
            this.oIBField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0", IncludeInSchema=false)]
public enum ItemsChoiceType1 {
    
    /// <remarks/>
    Ime,
    
    /// <remarks/>
    Naziv,
    
    /// <remarks/>
    Prezime,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0")]
public partial class sObracunSastavio {
    
    private string imeField;
    
    private string prezimeField;
    
    private sPoslovniSubjekt poslovniSubjektField;
    
    /// <remarks/>
    public string Ime {
        get {
            return this.imeField;
        }
        set {
            this.imeField = value;
        }
    }
    
    /// <remarks/>
    public string Prezime {
        get {
            return this.prezimeField;
        }
        set {
            this.prezimeField = value;
        }
    }
    
    /// <remarks/>
    public sPoslovniSubjekt PoslovniSubjekt {
        get {
            return this.poslovniSubjektField;
        }
        set {
            this.poslovniSubjektField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0")]
public partial class sPoslovniSubjektProsireno {
    
    private string[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private string itemField;
    
    private ItemChoiceType itemElementNameField;
    
    private sAdresa adresaField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Ime", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Naziv", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prezime", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OIB", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PDVID", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    public sAdresa Adresa {
        get {
            return this.adresaField;
        }
        set {
            this.adresaField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    Ime,
    
    /// <remarks/>
    Naziv,
    
    /// <remarks/>
    Prezime,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    OIB,
    
    /// <remarks/>
    PDVID,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0")]
public partial class sRazdoblje {
    
    private System.DateTime datumOdField;
    
    private System.DateTime datumDoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DatumOd {
        get {
            return this.datumOdField;
        }
        set {
            this.datumOdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DatumDo {
        get {
            return this.datumDoField;
        }
        set {
            this.datumDoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacPDV/v9-0")]
public partial class sZaglavlje {
    
    private sRazdoblje razdobljeField;
    
    private sPoslovniSubjektProsireno obveznikField;
    
    private sObracunSastavio obracunSastavioField;
    
    private string ispostavaField;
    
    private string napomenaField;
    
    private sZastupnik zastupnikField;
    
    /// <remarks/>
    public sRazdoblje Razdoblje {
        get {
            return this.razdobljeField;
        }
        set {
            this.razdobljeField = value;
        }
    }
    
    /// <remarks/>
    public sPoslovniSubjektProsireno Obveznik {
        get {
            return this.obveznikField;
        }
        set {
            this.obveznikField = value;
        }
    }
    
    /// <remarks/>
    public sObracunSastavio ObracunSastavio {
        get {
            return this.obracunSastavioField;
        }
        set {
            this.obracunSastavioField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="token")]
    public string Ispostava {
        get {
            return this.ispostavaField;
        }
        set {
            this.ispostavaField = value;
        }
    }
    
    /// <remarks/>
    public string Napomena {
        get {
            return this.napomenaField;
        }
        set {
            this.napomenaField = value;
        }
    }
    
    /// <remarks/>
    public sZastupnik Zastupnik {
        get {
            return this.zastupnikField;
        }
        set {
            this.zastupnikField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sAdresantTemeljni {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sTipTemeljni {
    
    private string dcField;
    
    private tTip valueField;
    
    public sTipTemeljni() {
        this.dcField = "http://purl.org/dc/elements/1.1/type";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public tTip Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1")]
public enum tTip {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Elektronički obrazac")]
    Elektroničkiobrazac,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(sUskladjenost))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sUskladjenostTemeljni {
    
    private string dcField;
    
    private string valueField;
    
    public sUskladjenostTemeljni() {
        this.dcField = "http://purl.org/dc/terms/conformsTo";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sUskladjenost : sUskladjenostTemeljni {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sIdentifikatorTemeljni {
    
    private string dcField;
    
    private string valueField;
    
    public sIdentifikatorTemeljni() {
        this.dcField = "http://purl.org/dc/elements/1.1/identifier";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sJezikTemeljni {
    
    private string dcField;
    
    private tJezik valueField;
    
    public sJezikTemeljni() {
        this.dcField = "http://purl.org/dc/elements/1.1/language";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public tJezik Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1")]
public enum tJezik {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("hr-HR")]
    hrHR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sFormatTemeljni {
    
    private string dcField;
    
    private tFormat valueField;
    
    public sFormatTemeljni() {
        this.dcField = "http://purl.org/dc/elements/1.1/format";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public tFormat Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1")]
public enum tFormat {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("text/xml")]
    textxml,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sDatumTemeljni {
    
    private string dcField;
    
    private System.DateTime valueField;
    
    public sDatumTemeljni() {
        this.dcField = "http://purl.org/dc/elements/1.1/date";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public System.DateTime Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sAutorTemeljni {
    
    private string dcField;
    
    private string valueField;
    
    public sAutorTemeljni() {
        this.dcField = "http://purl.org/dc/elements/1.1/creator";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
