//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v2-0")]
[System.Xml.Serialization.XmlRootAttribute("ObrazacURA", Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v2-0", IsNullable=false)]
public partial class sObrazacURA {
    
    private sURAmetapodaci metapodaciField;
    
    private sZaglavlje zaglavljeField;
    
    private sTijelo tijeloField;
    
    private string verzijaShemeField;
    
    public sObrazacURA() {
        this.verzijaShemeField = "2.0";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
    public sURAmetapodaci Metapodaci {
        get {
            return this.metapodaciField;
        }
        set {
            this.metapodaciField = value;
        }
    }
    
    /// <remarks/>
    public sZaglavlje Zaglavlje {
        get {
            return this.zaglavljeField;
        }
        set {
            this.zaglavljeField = value;
        }
    }
    
    /// <remarks/>
    public sTijelo Tijelo {
        get {
            return this.tijeloField;
        }
        set {
            this.tijeloField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string verzijaSheme {
        get {
            return this.verzijaShemeField;
        }
        set {
            this.verzijaShemeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
[System.Xml.Serialization.XmlRootAttribute("Metapodaci", Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0", IsNullable=false)]
public partial class sURAmetapodaci {
    
    private sNaslovTemeljni naslovField;
    
    private sAutorTemeljni autorField;
    
    private sDatumTemeljni datumField;
    
    private sFormatTemeljni formatField;
    
    private sJezikTemeljni jezikField;
    
    private sIdentifikatorTemeljni identifikatorField;
    
    private sUskladjenost uskladjenostField;
    
    private sTipTemeljni tipField;
    
    private sAdresantTemeljni adresantField;
    
    /// <remarks/>
    public sNaslovTemeljni Naslov {
        get {
            return this.naslovField;
        }
        set {
            this.naslovField = value;
        }
    }
    
    /// <remarks/>
    public sAutorTemeljni Autor {
        get {
            return this.autorField;
        }
        set {
            this.autorField = value;
        }
    }
    
    /// <remarks/>
    public sDatumTemeljni Datum {
        get {
            return this.datumField;
        }
        set {
            this.datumField = value;
        }
    }
    
    /// <remarks/>
    public sFormatTemeljni Format {
        get {
            return this.formatField;
        }
        set {
            this.formatField = value;
        }
    }
    
    /// <remarks/>
    public sJezikTemeljni Jezik {
        get {
            return this.jezikField;
        }
        set {
            this.jezikField = value;
        }
    }
    
    /// <remarks/>
    public sIdentifikatorTemeljni Identifikator {
        get {
            return this.identifikatorField;
        }
        set {
            this.identifikatorField = value;
        }
    }
    
    /// <remarks/>
    public sUskladjenost Uskladjenost {
        get {
            return this.uskladjenostField;
        }
        set {
            this.uskladjenostField = value;
        }
    }
    
    /// <remarks/>
    public sTipTemeljni Tip {
        get {
            return this.tipField;
        }
        set {
            this.tipField = value;
        }
    }
    
    /// <remarks/>
    public sAdresantTemeljni Adresant {
        get {
            return this.adresantField;
        }
        set {
            this.adresantField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sNaslovTemeljni {
    
    private string dcField;
    
    private string valueField;
    
    public sNaslovTemeljni() {
        this.dcField = "http://purl.org/dc/elements/1.1/title";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v2-0")]
public partial class sRacuniUkupno {
    
    private decimal u19Field;
    
    private decimal u8Field;
    
    private decimal u9Field;
    
    private decimal u10Field;
    
    private decimal u11Field;
    
    private decimal u12Field;
    
    private decimal u13Field;
    
    private decimal u14Field;
    
    private decimal u15Field;
    
    private decimal u16Field;
    
    private decimal u17Field;
    
    private decimal u18Field;
    
    /// <remarks/>
    public decimal U19 {
        get {
            return this.u19Field;
        }
        set {
            this.u19Field = value;
        }
    }
    
    /// <remarks/>
    public decimal U8 {
        get {
            return this.u8Field;
        }
        set {
            this.u8Field = value;
        }
    }
    
    /// <remarks/>
    public decimal U9 {
        get {
            return this.u9Field;
        }
        set {
            this.u9Field = value;
        }
    }
    
    /// <remarks/>
    public decimal U10 {
        get {
            return this.u10Field;
        }
        set {
            this.u10Field = value;
        }
    }
    
    /// <remarks/>
    public decimal U11 {
        get {
            return this.u11Field;
        }
        set {
            this.u11Field = value;
        }
    }
    
    /// <remarks/>
    public decimal U12 {
        get {
            return this.u12Field;
        }
        set {
            this.u12Field = value;
        }
    }
    
    /// <remarks/>
    public decimal U13 {
        get {
            return this.u13Field;
        }
        set {
            this.u13Field = value;
        }
    }
    
    /// <remarks/>
    public decimal U14 {
        get {
            return this.u14Field;
        }
        set {
            this.u14Field = value;
        }
    }
    
    /// <remarks/>
    public decimal U15 {
        get {
            return this.u15Field;
        }
        set {
            this.u15Field = value;
        }
    }
    
    /// <remarks/>
    public decimal U16 {
        get {
            return this.u16Field;
        }
        set {
            this.u16Field = value;
        }
    }
    
    /// <remarks/>
    public decimal U17 {
        get {
            return this.u17Field;
        }
        set {
            this.u17Field = value;
        }
    }
    
    /// <remarks/>
    public decimal U18 {
        get {
            return this.u18Field;
        }
        set {
            this.u18Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v2-0")]
public partial class sRacun {
    
    private string r1Field;
    
    private string r2Field;
    
    private System.DateTime r3Field;
    
    private string r4Field;
    
    private string r5Field;
    
    private int r6Field;
    
    private string r7Field;
    
    private decimal r19Field;
    
    private decimal r8Field;
    
    private decimal r9Field;
    
    private decimal r10Field;
    
    private decimal r11Field;
    
    private decimal r12Field;
    
    private decimal r13Field;
    
    private decimal r14Field;
    
    private decimal r15Field;
    
    private decimal r16Field;
    
    private decimal r17Field;
    
    private decimal r18Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="nonNegativeInteger")]
    public string R1 {
        get {
            return this.r1Field;
        }
        set {
            this.r1Field = value;
        }
    }
    
    /// <remarks/>
    public string R2 {
        get {
            return this.r2Field;
        }
        set {
            this.r2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime R3 {
        get {
            return this.r3Field;
        }
        set {
            this.r3Field = value;
        }
    }
    
    /// <remarks/>
    public string R4 {
        get {
            return this.r4Field;
        }
        set {
            this.r4Field = value;
        }
    }
    
    /// <remarks/>
    public string R5 {
        get {
            return this.r5Field;
        }
        set {
            this.r5Field = value;
        }
    }
    
    /// <remarks/>
    public int R6 {
        get {
            return this.r6Field;
        }
        set {
            this.r6Field = value;
        }
    }
    
    /// <remarks/>
    public string R7 {
        get {
            return this.r7Field;
        }
        set {
            this.r7Field = value;
        }
    }
    
    /// <remarks/>
    public decimal R19 {
        get {
            return this.r19Field;
        }
        set {
            this.r19Field = value;
        }
    }
    
    /// <remarks/>
    public decimal R8 {
        get {
            return this.r8Field;
        }
        set {
            this.r8Field = value;
        }
    }
    
    /// <remarks/>
    public decimal R9 {
        get {
            return this.r9Field;
        }
        set {
            this.r9Field = value;
        }
    }
    
    /// <remarks/>
    public decimal R10 {
        get {
            return this.r10Field;
        }
        set {
            this.r10Field = value;
        }
    }
    
    /// <remarks/>
    public decimal R11 {
        get {
            return this.r11Field;
        }
        set {
            this.r11Field = value;
        }
    }
    
    /// <remarks/>
    public decimal R12 {
        get {
            return this.r12Field;
        }
        set {
            this.r12Field = value;
        }
    }
    
    /// <remarks/>
    public decimal R13 {
        get {
            return this.r13Field;
        }
        set {
            this.r13Field = value;
        }
    }
    
    /// <remarks/>
    public decimal R14 {
        get {
            return this.r14Field;
        }
        set {
            this.r14Field = value;
        }
    }
    
    /// <remarks/>
    public decimal R15 {
        get {
            return this.r15Field;
        }
        set {
            this.r15Field = value;
        }
    }
    
    /// <remarks/>
    public decimal R16 {
        get {
            return this.r16Field;
        }
        set {
            this.r16Field = value;
        }
    }
    
    /// <remarks/>
    public decimal R17 {
        get {
            return this.r17Field;
        }
        set {
            this.r17Field = value;
        }
    }
    
    /// <remarks/>
    public decimal R18 {
        get {
            return this.r18Field;
        }
        set {
            this.r18Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v2-0")]
public partial class sTijelo {
    
    private sRacun[] racuniField;
    
    private sRacuniUkupno ukupnoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("R", IsNullable=false)]
    public sRacun[] Racuni {
        get {
            return this.racuniField;
        }
        set {
            this.racuniField = value;
        }
    }
    
    /// <remarks/>
    public sRacuniUkupno Ukupno {
        get {
            return this.ukupnoField;
        }
        set {
            this.ukupnoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v2-0")]
public partial class sPoslovniSubjekt {
    
    private string oIBField;
    
    private string[] itemsField;
    
    private ItemsChoiceType1[] itemsElementNameField;
    
    /// <remarks/>
    public string OIB {
        get {
            return this.oIBField;
        }
        set {
            this.oIBField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Ime", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Naziv", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prezime", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType1[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v2-0", IncludeInSchema=false)]
public enum ItemsChoiceType1 {
    
    /// <remarks/>
    Ime,
    
    /// <remarks/>
    Naziv,
    
    /// <remarks/>
    Prezime,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v2-0")]
public partial class sIspunjavatelj {
    
    private string imeField;
    
    private string prezimeField;
    
    private sPoslovniSubjekt poslovniSubjektField;
    
    /// <remarks/>
    public string Ime {
        get {
            return this.imeField;
        }
        set {
            this.imeField = value;
        }
    }
    
    /// <remarks/>
    public string Prezime {
        get {
            return this.prezimeField;
        }
        set {
            this.prezimeField = value;
        }
    }
    
    /// <remarks/>
    public sPoslovniSubjekt PoslovniSubjekt {
        get {
            return this.poslovniSubjektField;
        }
        set {
            this.poslovniSubjektField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v2-0")]
public partial class sAdresa {
    
    private string mjestoField;
    
    private string ulicaField;
    
    private string brojField;
    
    private string dodatakKucnomBrojuField;
    
    /// <remarks/>
    public string Mjesto {
        get {
            return this.mjestoField;
        }
        set {
            this.mjestoField = value;
        }
    }
    
    /// <remarks/>
    public string Ulica {
        get {
            return this.ulicaField;
        }
        set {
            this.ulicaField = value;
        }
    }
    
    /// <remarks/>
    public string Broj {
        get {
            return this.brojField;
        }
        set {
            this.brojField = value;
        }
    }
    
    /// <remarks/>
    public string DodatakKucnomBroju {
        get {
            return this.dodatakKucnomBrojuField;
        }
        set {
            this.dodatakKucnomBrojuField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v2-0")]
public partial class sPorezniObveznik {
    
    private string itemField;
    
    private ItemChoiceType itemElementNameField;
    
    private string[] itemsField;
    
    private ItemsChoiceType[] itemsElementNameField;
    
    private sAdresa adresaField;
    
    private string podrucjeDjelatnostiField;
    
    private string sifraDjelatnostiField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("OIB", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("PDVID", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
    public string Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemChoiceType ItemElementName {
        get {
            return this.itemElementNameField;
        }
        set {
            this.itemElementNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Ime", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Naziv", typeof(string))]
    [System.Xml.Serialization.XmlElementAttribute("Prezime", typeof(string))]
    [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
    public string[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemsElementName")]
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public ItemsChoiceType[] ItemsElementName {
        get {
            return this.itemsElementNameField;
        }
        set {
            this.itemsElementNameField = value;
        }
    }
    
    /// <remarks/>
    public sAdresa Adresa {
        get {
            return this.adresaField;
        }
        set {
            this.adresaField = value;
        }
    }
    
    /// <remarks/>
    public string PodrucjeDjelatnosti {
        get {
            return this.podrucjeDjelatnostiField;
        }
        set {
            this.podrucjeDjelatnostiField = value;
        }
    }
    
    /// <remarks/>
    public string SifraDjelatnosti {
        get {
            return this.sifraDjelatnostiField;
        }
        set {
            this.sifraDjelatnostiField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v2-0", IncludeInSchema=false)]
public enum ItemChoiceType {
    
    /// <remarks/>
    OIB,
    
    /// <remarks/>
    PDVID,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v2-0", IncludeInSchema=false)]
public enum ItemsChoiceType {
    
    /// <remarks/>
    Ime,
    
    /// <remarks/>
    Naziv,
    
    /// <remarks/>
    Prezime,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v2-0")]
public partial class sRazdoblje {
    
    private System.DateTime datumOdField;
    
    private System.DateTime datumDoField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DatumOd {
        get {
            return this.datumOdField;
        }
        set {
            this.datumOdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
    public System.DateTime DatumDo {
        get {
            return this.datumDoField;
        }
        set {
            this.datumDoField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/zahtjevi/ObrazacURA/v2-0")]
public partial class sZaglavlje {
    
    private sRazdoblje razdobljeField;
    
    private sPorezniObveznik obveznikField;
    
    private sIspunjavatelj obracunSastavioField;
    
    /// <remarks/>
    public sRazdoblje Razdoblje {
        get {
            return this.razdobljeField;
        }
        set {
            this.razdobljeField = value;
        }
    }
    
    /// <remarks/>
    public sPorezniObveznik Obveznik {
        get {
            return this.obveznikField;
        }
        set {
            this.obveznikField = value;
        }
    }
    
    /// <remarks/>
    public sIspunjavatelj ObracunSastavio {
        get {
            return this.obracunSastavioField;
        }
        set {
            this.obracunSastavioField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sAdresantTemeljni {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sTipTemeljni {
    
    private string dcField;
    
    private tTip valueField;
    
    public sTipTemeljni() {
        this.dcField = "http://purl.org/dc/elements/1.1/type";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public tTip Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1")]
public enum tTip {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("Elektronički obrazac")]
    Elektroničkiobrazac,
}

/// <remarks/>
[System.Xml.Serialization.XmlIncludeAttribute(typeof(sUskladjenost))]
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sUskladjenostTemeljni {
    
    private string dcField;
    
    private string valueField;
    
    public sUskladjenostTemeljni() {
        this.dcField = "http://purl.org/dc/terms/conformsTo";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sUskladjenost : sUskladjenostTemeljni {
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sIdentifikatorTemeljni {
    
    private string dcField;
    
    private string valueField;
    
    public sIdentifikatorTemeljni() {
        this.dcField = "http://purl.org/dc/elements/1.1/identifier";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sJezikTemeljni {
    
    private string dcField;
    
    private tJezik valueField;
    
    public sJezikTemeljni() {
        this.dcField = "http://purl.org/dc/elements/1.1/language";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public tJezik Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1")]
public enum tJezik {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("hr-HR")]
    hrHR,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sFormatTemeljni {
    
    private string dcField;
    
    private tFormat valueField;
    
    public sFormatTemeljni() {
        this.dcField = "http://purl.org/dc/elements/1.1/format";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public tFormat Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/TemeljniTipovi/v2-1")]
public enum tFormat {
    
    /// <remarks/>
    [System.Xml.Serialization.XmlEnumAttribute("text/xml")]
    textxml,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sDatumTemeljni {
    
    private string dcField;
    
    private System.DateTime valueField;
    
    public sDatumTemeljni() {
        this.dcField = "http://purl.org/dc/elements/1.1/date";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public System.DateTime Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://e-porezna.porezna-uprava.hr/sheme/Metapodaci/v2-0")]
public partial class sAutorTemeljni {
    
    private string dcField;
    
    private string valueField;
    
    public sAutorTemeljni() {
        this.dcField = "http://purl.org/dc/elements/1.1/creator";
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string dc {
        get {
            return this.dcField;
        }
        set {
            this.dcField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
