CREATE PROCEDURE [dbo].[spBookUraRest_Insert]
@Id INT,
@RedniBroj INT,
@Datum DATETIME2,
@BrojRacuna NVARCHAR(150),
@Storno BIT,
@StornoBroja INT,
@DatumRacuna DATETIME2,
@StarostRacuna INT,
@Dospijece DATETIME2,
@PlaniranaUplata DECIMAL(9,2),
@DatumUplate DATETIME2,
@ZaUplatu DECIMAL (9,2),
@NazivDobavljaca NVARCHAR(255),
@BrojPrimke INT,
@NapomenaORacunu NVARCHAR(255),
@NettoNabavnaVrijednost DECIMAL(9,2),
@SjedisteDobavljaca NVARCHAR(255),
@OIB NVARCHAR(11),
@IznosSPorezom DECIMAL(9,2),
@PoreznaOsnovica0 DECIMAL(9,2),
@PoreznaOsnovica5 DECIMAL(9,2),
@PretporezT5 DECIMAL(9,2),
@PoreznaOsnovica10 DECIMAL(9,2),
@PretporezT10 DECIMAL(9,2),
@PoreznaOsnovica13 DECIMAL(9,2),
@PretporezT13 DECIMAL(9,2),
@PoreznaOsnovica23 DECIMAL(9,2),
@PretporezT23 DECIMAL(9,2),
@PoreznaOsnovica25 DECIMAL(9,2),
@PretporezT25 DECIMAL(9,2),
@UkupniPretporez DECIMAL(9,2),
@MozeSeOdbiti DECIMAL(9,2),
@NeMozeSeOdbiti DECIMAL(9,2),
@IznosBezPoreza DECIMAL(9,2),
@ProlaznaStavka DECIMAL(9,2),
@Neoporezivo DECIMAL(9,2),
@CassaScontoPercent DECIMAL(9,2),
@CassaSconto DECIMAL(9,2),
@BrojOdobrenja NVARCHAR(50),
@OdobrenjaBezPDV NVARCHAR(50),
@OdobreniPDV DECIMAL(9,2),
@DatumPodnosenja DATETIME2,
@DatumIzvrsenja DATETIME2,
@UkupnoUplaceno DECIMAL(9,2),
@PreostaloZaUplatit DECIMAL(9,2),
@DospijeceDana INT,
@Knjizen BIT,
@TemeljnicaId INT
AS
BEGIN
	SET NOCOUNT ON;
	INSERT INTO BookUraRest (RedniBroj, Datum, BrojRacuna, Storno, StornoBroja, DatumRacuna, StarostRacuna, Dospijece, 
		PlaniranaUplata, DatumUplate, ZaUplatu, NazivDobavljaca, BrojPrimke, NapomenaORacunu, NettoNabavnaVrijednost, 
		SjedisteDobavljaca, OIB, IznosSPorezom, PoreznaOsnovica0, PoreznaOsnovica5, PretporezT5, PoreznaOsnovica10, PretporezT10, 
		PoreznaOsnovica13, PretporezT13, PoreznaOsnovica23, PretporezT23, PoreznaOsnovica25, PretporezT25, UkupniPretporez, 
		MozeSeOdbiti, NeMozeSeOdbiti, IznosBezPoreza, ProlaznaStavka, Neoporezivo, CassaScontoPercent, CassaSconto, BrojOdobrenja, 
		OdobrenjaBezPDV, OdobreniPDV, DatumPodnosenja, DatumIzvrsenja, UkupnoUplaceno, PreostaloZaUplatit, DospijeceDana, Knjizen,
		TemeljnicaId)
	VALUES (@RedniBroj, @Datum, @BrojRacuna, @Storno, @StornoBroja, @DatumRacuna, @StarostRacuna, @Dospijece, 
		@PlaniranaUplata, @DatumUplate, @ZaUplatu, @NazivDobavljaca, @BrojPrimke, @NapomenaORacunu, @NettoNabavnaVrijednost, 
		@SjedisteDobavljaca, @OIB, @IznosSPorezom, @PoreznaOsnovica0, @PoreznaOsnovica5, @PretporezT5, @PoreznaOsnovica10, @PretporezT10, 
		@PoreznaOsnovica13, @PretporezT13, @PoreznaOsnovica23, @PretporezT23, @PoreznaOsnovica25, @PretporezT25, @UkupniPretporez, 
		@MozeSeOdbiti, @NeMozeSeOdbiti, @IznosBezPoreza, @ProlaznaStavka, @Neoporezivo, @CassaScontoPercent, @CassaSconto, @BrojOdobrenja, 
		@OdobrenjaBezPDV, @OdobreniPDV, @DatumPodnosenja, @DatumIzvrsenja, @UkupnoUplaceno, @PreostaloZaUplatit, @DospijeceDana, @Knjizen,
		@TemeljnicaId)
END