CREATE TABLE [dbo].[BookIra]
(
	[Id] INT IDENTITY,
	[RedniBroj] INT NOT NULL,
	[BrojRacuna] NVARCHAR(250) NOT NULL,
	[Storno] BIT,
	[IzRacuna] INT,
	[Datum] DATETIME2 NOT NULL,
	[Dospijece] DATETIME2,
	[DatumZadnjeUplate] DATETIME2,
	[NazivISjedisteKupca] NVARCHAR(255),
	[Oib] NVARCHAR(11),
	[IznosSPdv] DECIMAL(9,2) NOT NULL,
	[OslobodjenoPdvEU] DECIMAL(9,2) NULL,
	[OslobodjenoPdvOstalo] DECIMAL(9,2) NULL,
	[ProlaznaStavka] DECIMAL(9,2) NULL,
	[PoreznaOsnovica0] DECIMAL(9,2) NULL,
	[PoreznaOsnovica5] DECIMAL(9,2) NULL,
	[Pdv5] DECIMAL(9,2) NULL,
	[PoreznaOsnovica10] DECIMAL(9,2) NULL,
	[Pdv10] DECIMAL(9,2) NULL,
	[PoreznaOsnovica13] DECIMAL(9,2) NULL,
	[Pdv13] DECIMAL(9,2) NULL,
	[PoreznaOsnovica23] DECIMAL(9,2) NULL,
	[Pdv23] DECIMAL(9,2) NULL,
	[PoreznaOsnovica25] DECIMAL(9,2) NULL,
	[Pdv25] DECIMAL(9,2) NULL,
	[UkupniPdv] DECIMAL(9,2) NULL,
	[UkupnoUplaceno] DECIMAL(9,2) NULL,
	[PreostaloZaUplatit] DECIMAL(9,2) NULL,
	[NapomenaORacunu] NVARCHAR(255),
	[ZaprimljenUHzzo] DATETIME2,
	[DanaOdZaprimanja]INT,
	[DanaNeplacanja] INT,
	[Knjizen] BIT
)
